---

- hosts: all
  become: true
  tasks:

  - name: update cache, install python3-setuptools
    apt:
      name: 
        - python3-setuptools
      state: present
      update_cache: yes
      cache_valid_time: 3600
  
  - name: Uninstall apt Ansible
    apt:
      name:
        - ansible
        - ansible-core
      state: absent
    when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS", "Raspbian"]

  - name: Install Ansible using pip
    ansible.builtin.pip:
      name: ansible
      state: latest
