---

- hosts: 
    - docker
    - ansible
  
  become: true

  tasks:

    - name: "install ansible galaxy Docker"
      community.general.ansible_galaxy_install:
        type: collection
        name: community.docker
