---

- hosts: octoprint
  become: true
  tasks:

  - name: update cache
    apt:
      update_cache: yes
      name: 
        - cpulimit
      state: present
#    when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]


