---

  hosts: all
  become: yes
  tasks:

  - import_tasks: syncthing.yml

  - name: update cache
    apt:
      update_cache: yes
      name: 
        - samba
      state: present
    when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]

  - name: add group smbusers
    group:
      name: smbusers
      state: present

  - name: add user "dani"
    user: 
      name: dani
      create_home: no
      password: vCxMJJzZzP45U
      shell: /sbin/nologin
      system: no
      state: present

  - name: add users to smbusers-group
    user:
      name: '{{ item }}'
      groups: smbusers
      append: yes
    loop:
      - manu
      - dani
      - sync

#  - name: enable syncthing
#    systemd:
#      name: 
#      state: started
#      enabled: true

#  - name: restart syncthing
#    systemd:
#      name: syncthing@sync
#      state: restarted
#      enabled: true
