---

- hosts: all
  become: true
  tasks:

#  - name: generate locale
#    locale_gen:
#      name: en_US.UTF-8
#      state: present  
#
#  - name: set US as default locale
#    command: localectl set-locale LANG=en_US.UTF-8 #LC_ALL=en_US.UTF-8

  - name: select default locale
    debconf:
      name: locales
      question: locales/default_environment_locale
      value: en_US.UTF-8
      vtype: select
    notify:
      - rebuild locales database

  - name: /etc/locale.gen
    lineinfile:
      dest: /etc/locale.gen
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
      state: "{{ item.state }}"
    with_items:
      - { regexp: '^#? ?de_DE ISO-8859-1', line: 'de_DE ISO-8859-1', state: present }
      - { regexp: '^#? ?de_DE.UTF-8 UTF-8', line: 'de_DE.UTF-8 UTF-8', state: present }
      - { regexp: '^#? ?de_DE@euro ISO-8859-15', line: 'de_DE@euro ISO-8859-15', state: present }
      - { regexp: '^#? ?en_GB ISO-8859-1', line: 'en_GB ISO-8859-1', state: present }
      - { regexp: '^#? ?en_GB.ISO-8859-15 ISO-8859-15', line: 'en_GB.ISO-8859-15 ISO-8859-15', state: present }
      - { regexp: '^#? ?en_GB.UTF-8 UTF-8', line: 'en_GB.UTF-8 UTF-8', state: present }
      - { regexp: '^#? ?en_US ISO-8859-1', line: 'en_US ISO-8859-1', state: present }
      - { regexp: '^#? ?en_US.ISO-8859-15 ISO-8859-15', line: 'en_US.ISO-8859-15 ISO-8859-15', state: present }
      - { regexp: '^#? ?en_US.UTF-8 UTF-8', line: 'en_US.UTF-8 UTF-8', state: present }
    notify:
      - rebuild locales database

  - name: rebuild locales database
    command: "{{ item }}"
    with_items:
      - dpkg-reconfigure locales -f noninteractive
      - /usr/sbin/locale-gen
