---

- hosts: all
  become: true
  tasks:

  - name: import apt key
    apt_key:
      url: https://syncthing.net/release-key.gpg
      state: present
    when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]
  
  - name: install syncthing repository
    apt_repository: 
      repo: deb https://apt.syncthing.net/ syncthing stable
      state: present
    when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]

  - name: update cache
    apt:
      update_cache: yes
      name: 
        - syncthing
      state: present
    when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]

  - name: add user
    user: 
      name: sync
      shell: /bin/bash
      system: yes
  
  - name: enable syncthing
    systemd:
      name: syncthing@sync
      state: started
      enabled: true


  - name: change gui listen address
    replace:
      path: /home/sync/.config/syncthing
      regexp: '<address>127.0.0.1:8384</address>'
      replace: '<address>0.0.0.0:8384</address>'
      backup: yes

  - name: restart syncthing
    systemd:
      name: syncthing@sync
      state: restarted
      enabled: true