---

- hosts: all
  become: true
  tasks:

  - name: import apt key
    apt_key:
      url: https://syncthing.net/release-key.gpg
      state: present
    when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]
  
  - name: install syncthing repository
    apt_repository: 
      repo: deb https://apt.syncthing.net/ syncthing stable
      state: present
    when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]

  - name: update cache
    apt:
      update_cache: yes
      name: 
        - syncthing
      state: present
    when: ansible_distribution in ["Debian", "Ubuntu", "Pop!_OS"]

  - name: add user
    user: 
      name: sync
      home: /home/sync
#      move_home: yes
#      shell: /bin/bash
      system: yes
      state: present
  
  - name: create systemd/service exists
    file: 
      path: /etc/systemd/service
      state: directory
      owner: root

  - name: copy syncthing service file
    copy:
      src: syncthing@.service
      dest: /etc/systemd/service/syncthing@.service
      owner: root
      group: root
      mode: 0600

  - name: enable syncthing
    systemd:
      name: syncthing@sync
      state: started
      enabled: true


  - name: change gui listen address
    replace:
      path: /home/sync/.config/syncthing/config.xml
      regexp: '<address>127.0.0.1:8384</address>'
      replace: '<address>0.0.0.0:8384</address>'
      backup: yes

  - name: restart syncthing
    systemd:
      name: syncthing@sync
      state: restarted
      enabled: true
