---

- hosts: all
  become: true
  tasks:

  - name: update cache
    apt:
      update_cache: yes
      cache_valid_time: 3600

  
  - name: full upgrade
    apt:
      upgrade: full

  - name: autoremove
    apt:
      autoremove: yes
    
  - name: clean apt cache
    apt:
      autoclean: yes
    
